-- AUTO-GENERATED by generate_calc_views.py — do not edit by hand.
-- Source calcs: calcs/CustodyPositionsCalc/
-- Regenerate: python generate_calc_views.py --generate-dbt

WITH AssetClass AS (
  -- CALC: AssetClass
  -- Broad asset classification used for portfolio risk bucketing and statement layout.
  --   Stablecoin  → USDC, USDT (USD-pegged, near-zero market risk)
  --   Layer1      → BTC, ETH, SOL (L1 settlement layer assets)
  --   AltCoin     → ADA, MATIC, ATOM, DOT (higher volatility, protocol-specific risk)
  
  SELECT
    CustodyPositions.ID AS ID
    , CASE
        WHEN CustodyPositions.AssetId IN ('ASSET_USDC', 'ASSET_USDT') THEN 'Stablecoin'
        WHEN CustodyPositions.AssetId IN ('ASSET_BTC', 'ASSET_ETH', 'ASSET_SOL') THEN 'Layer1'
        ELSE 'AltCoin'
      END AS AssetClass
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, DaysInPeriod AS (
  -- CALC: DaysInPeriod
  -- Number of calendar days in the month the position date falls in.
  -- Used to prorate daily AUM for custody fee calculations:
  -- DailyAUM = ValuationUSD / DaysInPeriod × (days held in period).
  
  SELECT
    CustodyPositions.ID AS ID
    , DATE_DIFF(
        LAST_DAY(CustodyPositions.PositionDate, MONTH),
        DATE_TRUNC(CustodyPositions.PositionDate, MONTH),
        DAY
      ) + 1 AS DaysInPeriod
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, IsPeriodEnd AS (
  -- CALC: IsPeriodEnd
  -- TRUE when the position snapshot date is the last day of its calendar month.
  -- Period-end rows are the authoritative balance for monthly client statements.
  -- Non-period-end rows are intra-month snapshots used for daily repricing only.
  
  SELECT
    CustodyPositions.ID AS ID
    , CustodyPositions.PositionDate = LAST_DAY(CustodyPositions.PositionDate, MONTH) AS IsPeriodEnd
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, IsStablecoin AS (
  -- CALC: IsStablecoin
  -- TRUE when the position asset is a USD-pegged stablecoin (USDC or USDT).
  -- Stablecoin positions carry near-zero market risk and are reported separately
  -- from volatile crypto holdings on client statements.
  
  SELECT
    CustodyPositions.ID AS ID
    , CustodyPositions.AssetId IN ('ASSET_USDC', 'ASSET_USDT') AS IsStablecoin
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, PositionAgeMonths AS (
  -- CALC: PositionAgeMonths
  -- Months elapsed between the position record's creation date and its snapshot date.
  -- Zero indicates the position was created in the same month it was first snapshotted.
  -- Used for position vintage analysis and long-standing balance trend reporting.
  
  SELECT
    CustodyPositions.ID AS ID
    , DATE_DIFF(
        CustodyPositions.PositionDate,
        DATE(CustodyPositions.CreatedAt),
        MONTH
      ) AS PositionAgeMonths
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, PositionPeriod AS (
  -- CALC: PositionPeriod
  -- The calendar month a custody position snapshot belongs to.
  -- Used to group daily snapshots into monthly period-end balances
  -- in the CustodyBalancesByPeriod business view.
  
  SELECT
    CustodyPositions.ID AS ID
    , DATE_TRUNC(CustodyPositions.PositionDate, MONTH) AS PositionPeriod
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, PositionQuarter AS (
  -- CALC: PositionQuarter
  -- The calendar quarter a custody position snapshot belongs to.
  -- Used for quarterly roll-up reporting and quarter-over-quarter balance comparisons.
  
  SELECT
    CustodyPositions.ID AS ID
    , DATE_TRUNC(CustodyPositions.PositionDate, QUARTER) AS PositionQuarter
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, PositionYear AS (
  -- CALC: PositionYear
  -- The calendar year a custody position snapshot belongs to.
  -- Used for year-end reporting and annual AUM trend analysis.
  
  SELECT
    CustodyPositions.ID AS ID
    , EXTRACT(YEAR FROM CustodyPositions.PositionDate) AS PositionYear
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, ValuationTier AS (
  -- CALC: ValuationTier
  -- Client-segment tier based on the USD valuation of the position.
  -- Used for fee tier assignment and statement routing.
  --   Institutional  ≥ $10M
  --   Prime          ≥ $1M
  --   Standard       < $1M
  
  SELECT
    CustodyPositions.ID AS ID
    , CASE
        WHEN CustodyPositions.ValuationUSD >= 10000000 THEN 'Institutional'
        WHEN CustodyPositions.ValuationUSD >= 1000000  THEN 'Prime'
        ELSE 'Standard'
      END AS ValuationTier
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
, ValuationUSDRounded AS (
  -- CALC: ValuationUSDRounded
  -- ValuationUSD rounded to the nearest cent (2 decimal places).
  -- Raw ValuationUSD preserves full BIGNUMERIC precision for reconciliation.
  -- This rounded version is used for display on client-facing statements.
  
  SELECT
    CustodyPositions.ID AS ID
    , ROUND(CustodyPositions.ValuationUSD, 2) AS ValuationUSDRounded
  FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS CustodyPositions
)
SELECT
  Base.ID
  , AssetClass.AssetClass
  , DaysInPeriod.DaysInPeriod
  , IsPeriodEnd.IsPeriodEnd
  , IsStablecoin.IsStablecoin
  , PositionAgeMonths.PositionAgeMonths
  , PositionPeriod.PositionPeriod
  , PositionQuarter.PositionQuarter
  , PositionYear.PositionYear
  , ValuationTier.ValuationTier
  , ValuationUSDRounded.ValuationUSDRounded
FROM {{ source('anchorage_data_platform', 'CustodyPositions') }} AS Base
LEFT JOIN AssetClass
  ON AssetClass.ID = Base.ID
LEFT JOIN DaysInPeriod
  ON DaysInPeriod.ID = Base.ID
LEFT JOIN IsPeriodEnd
  ON IsPeriodEnd.ID = Base.ID
LEFT JOIN IsStablecoin
  ON IsStablecoin.ID = Base.ID
LEFT JOIN PositionAgeMonths
  ON PositionAgeMonths.ID = Base.ID
LEFT JOIN PositionPeriod
  ON PositionPeriod.ID = Base.ID
LEFT JOIN PositionQuarter
  ON PositionQuarter.ID = Base.ID
LEFT JOIN PositionYear
  ON PositionYear.ID = Base.ID
LEFT JOIN ValuationTier
  ON ValuationTier.ID = Base.ID
LEFT JOIN ValuationUSDRounded
  ON ValuationUSDRounded.ID = Base.ID
