-- AUTO-GENERATED by generate_calc_views.py — do not edit by hand.
-- Source calcs: calcs/FeeEventsCalc/
-- Regenerate: python generate_calc_views.py --generate-dbt

WITH EffectiveRateBps AS (
  -- CALC: EffectiveRateBps
  -- Actual effective fee rate in basis points, derived from the charged fee amount
  -- and the AUM at the time of billing. Differs from contracted BasisPoints when
  -- proration or waivers are applied. Used for fee audit and rate compliance checks.
  
  SELECT
    FeeEvents.ID AS ID
    , SAFE_DIVIDE(FeeEvents.FeeAmountUSD, FeeEvents.AumAtBilling) * 10000 AS EffectiveRateBps
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, FeeAmountUSDRounded AS (
  -- CALC: FeeAmountUSDRounded
  -- FeeAmountUSD rounded to the nearest cent (2 decimal places).
  -- The raw value preserves full NUMERIC precision for internal reconciliation.
  -- This rounded value is used for all client-facing statement line items.
  
  SELECT
    FeeEvents.ID AS ID
    , ROUND(FeeEvents.FeeAmountUSD, 2) AS FeeAmountUSDRounded
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, FeePeriod AS (
  -- CALC: FeePeriod
  -- The calendar month a fee event's billing period starts in.
  -- Used to group individual fee events into monthly accrual buckets
  -- in the FeeAccrualsByPeriod business view.
  
  SELECT
    FeeEvents.ID AS ID
    , DATE_TRUNC(FeeEvents.FeePeriodStart, MONTH) AS FeePeriod
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, FeePeriodDays AS (
  -- CALC: FeePeriodDays
  -- Number of calendar days in the fee billing period (end - start).
  -- Standard custody billing period = 28-31 days. Values outside this range
  -- flag irregular billing windows that require ops review before statement delivery.
  
  SELECT
    FeeEvents.ID AS ID
    , DATE_DIFF(FeeEvents.FeePeriodEnd, FeeEvents.FeePeriodStart, DAY) AS FeePeriodDays
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, FeeQuarter AS (
  -- CALC: FeeQuarter
  -- The calendar quarter the fee billing period starts in.
  -- Used for quarterly fee revenue roll-ups and quarter-over-quarter accrual comparisons.
  
  SELECT
    FeeEvents.ID AS ID
    , DATE_TRUNC(FeeEvents.FeePeriodStart, QUARTER) AS FeeQuarter
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, FeeYear AS (
  -- CALC: FeeYear
  -- The calendar year the fee billing period starts in.
  -- Used for annual revenue reporting and YoY fee trend analysis.
  
  SELECT
    FeeEvents.ID AS ID
    , EXTRACT(YEAR FROM FeeEvents.FeePeriodStart) AS FeeYear
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, IsAccruedNotBilled AS (
  -- CALC: IsAccruedNotBilled
  -- TRUE when a fee has been recognized (accrued) but not yet invoiced to the client.
  -- ACCRUED fees appear on internal P&L but must NOT appear on client-facing statements
  -- until BillingStatus transitions to BILLED. Compliance gate for statement delivery.
  
  SELECT
    FeeEvents.ID AS ID
    , UPPER(FeeEvents.BillingStatus) = 'ACCRUED' AS IsAccruedNotBilled
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, IsCustodyFee AS (
  -- CALC: IsCustodyFee
  -- TRUE when the fee type is a direct custody service charge.
  -- Custody fees are the primary revenue line. Non-custody types include
  -- staking service fees, wire fees, and one-time setup charges.
  
  SELECT
    FeeEvents.ID AS ID
    , UPPER(FeeEvents.FeeType) = 'CUSTODY' AS IsCustodyFee
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, IsFullyBilled AS (
  -- CALC: IsFullyBilled
  -- TRUE when a fee event has been invoiced and collected from the client.
  -- FALSE = accrued but not yet billed. Compliance gate: all fees must be
  -- TRUE before a period can be marked RECONCILED.
  
  SELECT
    FeeEvents.ID AS ID
    , UPPER(FeeEvents.BillingStatus) = 'BILLED' AS IsFullyBilled
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
, IsWaived AS (
  -- CALC: IsWaived
  -- TRUE when the fee has been explicitly waived (credited back) for the client.
  -- Waived fees must still appear on statements as a zero-amount line item with
  -- WAIVED status for regulatory disclosure — they cannot be silently omitted.
  
  SELECT
    FeeEvents.ID AS ID
    , UPPER(FeeEvents.BillingStatus) = 'WAIVED' AS IsWaived
  FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS FeeEvents
)
SELECT
  Base.ID
  , EffectiveRateBps.EffectiveRateBps
  , FeeAmountUSDRounded.FeeAmountUSDRounded
  , FeePeriod.FeePeriod
  , FeePeriodDays.FeePeriodDays
  , FeeQuarter.FeeQuarter
  , FeeYear.FeeYear
  , IsAccruedNotBilled.IsAccruedNotBilled
  , IsCustodyFee.IsCustodyFee
  , IsFullyBilled.IsFullyBilled
  , IsWaived.IsWaived
FROM {{ source('anchorage_data_platform', 'FeeEvents') }} AS Base
LEFT JOIN EffectiveRateBps
  ON EffectiveRateBps.ID = Base.ID
LEFT JOIN FeeAmountUSDRounded
  ON FeeAmountUSDRounded.ID = Base.ID
LEFT JOIN FeePeriod
  ON FeePeriod.ID = Base.ID
LEFT JOIN FeePeriodDays
  ON FeePeriodDays.ID = Base.ID
LEFT JOIN FeeQuarter
  ON FeeQuarter.ID = Base.ID
LEFT JOIN FeeYear
  ON FeeYear.ID = Base.ID
LEFT JOIN IsAccruedNotBilled
  ON IsAccruedNotBilled.ID = Base.ID
LEFT JOIN IsCustodyFee
  ON IsCustodyFee.ID = Base.ID
LEFT JOIN IsFullyBilled
  ON IsFullyBilled.ID = Base.ID
LEFT JOIN IsWaived
  ON IsWaived.ID = Base.ID
