-- AUTO-GENERATED by generate_calc_views.py — do not edit by hand.
-- Source calcs: calcs/FinancialEventsCalc/
-- Regenerate: python generate_calc_views.py --generate-dbt

WITH EventPeriod AS (
  -- CALC: EventPeriod
  -- The calendar month a financial event's period date falls in.
  -- Used to aggregate the canonical event log to monthly period totals
  -- for reconciliation against reported position and fee figures.
  
  SELECT
    FinancialEvents.ID AS ID
    , DATE_TRUNC(FinancialEvents.PeriodDate, MONTH) AS EventPeriod
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, EventQuarter AS (
  -- CALC: EventQuarter
  -- The calendar quarter the financial event's period date falls in.
  -- Used for quarterly P&L aggregation and quarter-end reconciliation reporting.
  
  SELECT
    FinancialEvents.ID AS ID
    , DATE_TRUNC(FinancialEvents.PeriodDate, QUARTER) AS EventQuarter
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, EventYear AS (
  -- CALC: EventYear
  -- The calendar year the financial event's period date falls in.
  -- Used for annual financial reporting and year-over-year activity trend analysis.
  
  SELECT
    FinancialEvents.ID AS ID
    , EXTRACT(YEAR FROM FinancialEvents.PeriodDate) AS EventYear
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, IsCustodyEvent AS (
  -- CALC: IsCustodyEvent
  -- TRUE when the event originates from the custody product line.
  -- Used to partition the unified financial event log for custody-specific
  -- reconciliation against the CustodyPositions balance sheet.
  
  SELECT
    FinancialEvents.ID AS ID
    , UPPER(FinancialEvents.ProductLine) = 'CUSTODY' AS IsCustodyEvent
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, IsPending AS (
  -- CALC: IsPending
  -- TRUE when a financial event has not yet settled.
  -- Used in ReconciliationSummary to surface periods with open items
  -- before month-end close. Target state: zero pending events per period.
  
  SELECT
    FinancialEvents.ID AS ID
    , UPPER(FinancialEvents.Status) = 'PENDING' AS IsPending
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, IsSameDaySettle AS (
  -- CALC: IsSameDaySettle
  -- TRUE when the event settled on the same calendar day it was timestamped.
  -- Crypto-native events should typically be same-day. Non-same-day crypto events
  -- may indicate protocol delays or manual holds — surfaced for ops review.
  -- NULL when SettlementDate is NULL (event not yet settled).
  
  SELECT
    FinancialEvents.ID AS ID
    , DATE(FinancialEvents.EventTimestamp) = FinancialEvents.SettlementDate AS IsSameDaySettle
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, IsSettledFinancial AS (
  -- CALC: IsSettledFinancial
  -- TRUE when the financial event has reached final settlement.
  -- An event is only eligible for period-close inclusion once IsSettledFinancial = TRUE.
  -- IsPending and IsSettledFinancial are mutually exclusive; both FALSE = cancelled/voided.
  -- Named IsSettledFinancial (not IsSettled) to avoid collision with IsSettledStaking.
  
  SELECT
    FinancialEvents.ID AS ID
    , UPPER(FinancialEvents.Status) = 'SETTLED' AS IsSettledFinancial
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, IsStakingEvent AS (
  -- CALC: IsStakingEvent
  -- TRUE when the event originates from the staking product line.
  -- Staking events require a separate reconciliation path against the
  -- StakingEvents table — they cannot be reconciled via custody positions alone.
  
  SELECT
    FinancialEvents.ID AS ID
    , UPPER(FinancialEvents.ProductLine) = 'STAKING' AS IsStakingEvent
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, NetAmountRoundedFinancial AS (
  -- CALC: NetAmountRoundedFinancial
  -- NetAmount rounded to the nearest cent (2 decimal places).
  -- The raw NetAmount preserves BIGNUMERIC precision for reconciliation arithmetic.
  -- This rounded value is used for all client-facing statement line items.
  -- Named NetAmountRoundedFinancial (not NetAmountRounded) to avoid collision with NetAmountRoundedStaking.
  
  SELECT
    FinancialEvents.ID AS ID
    , ROUND(FinancialEvents.NetAmount, 2) AS NetAmountRoundedFinancial
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
, SettlementLagDays AS (
  -- CALC: SettlementLagDays
  -- Days elapsed from event timestamp (trade date) to settlement date.
  -- Standard expected lags: T+0 for crypto, T+1 for stablecoin, T+2 for OTC.
  -- Values > 5 are flagged for ops investigation before period close.
  -- NULL when SettlementDate is NULL (event not yet settled).
  
  SELECT
    FinancialEvents.ID AS ID
    , DATE_DIFF(
        FinancialEvents.SettlementDate,
        DATE(FinancialEvents.EventTimestamp),
        DAY
      ) AS SettlementLagDays
  FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS FinancialEvents
)
SELECT
  Base.ID
  , EventPeriod.EventPeriod
  , EventQuarter.EventQuarter
  , EventYear.EventYear
  , IsCustodyEvent.IsCustodyEvent
  , IsPending.IsPending
  , IsSameDaySettle.IsSameDaySettle
  , IsSettledFinancial.IsSettledFinancial
  , IsStakingEvent.IsStakingEvent
  , NetAmountRoundedFinancial.NetAmountRoundedFinancial
  , SettlementLagDays.SettlementLagDays
FROM {{ source('anchorage_data_platform', 'FinancialEvents') }} AS Base
LEFT JOIN EventPeriod
  ON EventPeriod.ID = Base.ID
LEFT JOIN EventQuarter
  ON EventQuarter.ID = Base.ID
LEFT JOIN EventYear
  ON EventYear.ID = Base.ID
LEFT JOIN IsCustodyEvent
  ON IsCustodyEvent.ID = Base.ID
LEFT JOIN IsPending
  ON IsPending.ID = Base.ID
LEFT JOIN IsSameDaySettle
  ON IsSameDaySettle.ID = Base.ID
LEFT JOIN IsSettledFinancial
  ON IsSettledFinancial.ID = Base.ID
LEFT JOIN IsStakingEvent
  ON IsStakingEvent.ID = Base.ID
LEFT JOIN NetAmountRoundedFinancial
  ON NetAmountRoundedFinancial.ID = Base.ID
LEFT JOIN SettlementLagDays
  ON SettlementLagDays.ID = Base.ID
