-- AUTO-GENERATED by generate_calc_views.py — do not edit by hand.
-- Source calcs: calcs/StakingEventsCalc/
-- Regenerate: python generate_calc_views.py --generate-dbt

WITH EarnPeriod AS (
  -- CALC: EarnPeriod
  -- The calendar month in which a staking reward was earned.
  -- Used to group events into monthly reward periods
  -- in the StakingRewardsByPeriod business view.
  
  SELECT
    StakingEvents.ID AS ID
    , DATE_TRUNC(StakingEvents.EarnDate, MONTH) AS EarnPeriod
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, EarnQuarter AS (
  -- CALC: EarnQuarter
  -- The calendar quarter in which a staking reward was earned.
  -- Used for quarterly staking yield reporting and quarter-over-quarter reward comparisons.
  
  SELECT
    StakingEvents.ID AS ID
    , DATE_TRUNC(StakingEvents.EarnDate, QUARTER) AS EarnQuarter
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, EarnYear AS (
  -- CALC: EarnYear
  -- The calendar year in which a staking reward was earned.
  -- Used for annual yield reporting and YoY staking revenue trend analysis.
  
  SELECT
    StakingEvents.ID AS ID
    , EXTRACT(YEAR FROM StakingEvents.EarnDate) AS EarnYear
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, IsBelowMinDistribution AS (
  -- CALC: IsBelowMinDistribution
  -- TRUE when the net reward amount is below the minimum distribution threshold (0.0001).
  -- Sub-threshold rewards are pooled and held until they cross the threshold rather than
  -- generating individual distribution events — reduces on-chain transaction noise.
  -- These rows appear on statements as "accumulated pending" rather than distributed.
  
  SELECT
    StakingEvents.ID AS ID
    , StakingEvents.NetAmount < 0.0001 AS IsBelowMinDistribution
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, IsDistributed AS (
  -- CALC: IsDistributed
  -- TRUE when the reward has been distributed to the client (DistributeDate is set).
  -- A reward can be settled (liquid) but not yet distributed — distribution requires
  -- client instruction or hits an auto-distribute threshold. Used to reconcile
  -- the settled pool against what has actually left the custodian ledger.
  
  SELECT
    StakingEvents.ID AS ID
    , StakingEvents.DistributeDate IS NOT NULL AS IsDistributed
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, IsSettledStaking AS (
  -- CALC: IsSettledStaking
  -- TRUE when a staking reward has been settled and is liquid/distributable to the client.
  -- FALSE (pending) = unbonding — appears as NetPen on client statements.
  -- Drives the settled vs pending split in StakingRewardsByPeriod.
  -- Named IsSettledStaking (not IsSettled) to avoid collision with IsSettledFinancial.
  
  SELECT
    StakingEvents.ID AS ID
    , UPPER(StakingEvents.RewardState) = 'SETTLED' AS IsSettledStaking
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, NetAmountRoundedStaking AS (
  -- CALC: NetAmountRoundedStaking
  -- NetAmount rounded to 8 decimal places (satoshi-level precision standard).
  -- The raw value preserves BIGNUMERIC precision for reconciliation arithmetic.
  -- This rounded value is used for client-facing statement reward line items.
  -- Named NetAmountRoundedStaking (not NetAmountRounded) to avoid collision with NetAmountRoundedFinancial.
  
  SELECT
    StakingEvents.ID AS ID
    , ROUND(StakingEvents.NetAmount, 8) AS NetAmountRoundedStaking
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, SettlePeriod AS (
  -- CALC: SettlePeriod
  -- The calendar month in which a staking reward settled (became liquid/distributable).
  -- NULL for rewards still in unbonding (SettleDate IS NULL / RewardState = 'pending').
  -- Drives the settled vs pending period split for NetPen exposure reporting.
  
  SELECT
    StakingEvents.ID AS ID
    , DATE_TRUNC(StakingEvents.SettleDate, MONTH) AS SettlePeriod
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
, UnbondingCategory AS (
  -- CALC: UnbondingCategory
  -- Classifies a staking event's unbonding risk tier based on the asset's
  -- unbonding period. Joins ReferenceAssets to get UnbondingDays.
  -- Used for NetPen exposure risk bucketing on client statements.
  --   Immediate  (0 days)  → ETH post-merge, ADA
  --   ShortTail  (1-3)     → SOL, MATIC
  --   MediumTail (4-21)    → ATOM
  --   LongTail   (>21)     → DOT — highest period-end timing risk
  
  SELECT
    StakingEvents.ID AS ID
    , CASE
        WHEN ReferenceAssets.UnbondingDays = 0 THEN 'Immediate'
        WHEN ReferenceAssets.UnbondingDays <= 3 THEN 'ShortTail'
        WHEN ReferenceAssets.UnbondingDays <= 21 THEN 'MediumTail'
        ELSE 'LongTail'
      END AS UnbondingCategory
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
  JOIN {{ source('anchorage_data_platform', 'ReferenceAssets') }} AS ReferenceAssets
    ON ReferenceAssets.AssetId = StakingEvents.AssetId
)
, UnbondingDays AS (
  -- CALC: UnbondingDays
  -- Actual number of days between earn date and settle date for this event.
  -- NULL while the reward is still in the unbonding queue (SettleDate not yet set).
  -- Used to validate that observed unbonding durations match protocol expectations
  -- (e.g., SOL ≈ 2-3 days, DOT ≈ 28 days) and flag oracle or pipeline delays.
  
  SELECT
    StakingEvents.ID AS ID
    , DATE_DIFF(StakingEvents.SettleDate, StakingEvents.EarnDate, DAY) AS UnbondingDays
  FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
)
SELECT
  Base.ID
  , EarnPeriod.EarnPeriod
  , EarnQuarter.EarnQuarter
  , EarnYear.EarnYear
  , IsBelowMinDistribution.IsBelowMinDistribution
  , IsDistributed.IsDistributed
  , IsSettledStaking.IsSettledStaking
  , NetAmountRoundedStaking.NetAmountRoundedStaking
  , SettlePeriod.SettlePeriod
  , UnbondingCategory.UnbondingCategory
  , UnbondingDays.UnbondingDays
FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS Base
LEFT JOIN EarnPeriod
  ON EarnPeriod.ID = Base.ID
LEFT JOIN EarnQuarter
  ON EarnQuarter.ID = Base.ID
LEFT JOIN EarnYear
  ON EarnYear.ID = Base.ID
LEFT JOIN IsBelowMinDistribution
  ON IsBelowMinDistribution.ID = Base.ID
LEFT JOIN IsDistributed
  ON IsDistributed.ID = Base.ID
LEFT JOIN IsSettledStaking
  ON IsSettledStaking.ID = Base.ID
LEFT JOIN NetAmountRoundedStaking
  ON NetAmountRoundedStaking.ID = Base.ID
LEFT JOIN SettlePeriod
  ON SettlePeriod.ID = Base.ID
LEFT JOIN UnbondingCategory
  ON UnbondingCategory.ID = Base.ID
LEFT JOIN UnbondingDays
  ON UnbondingDays.ID = Base.ID
