#!/usr/bin/env python3
"""
generate_report_models.py

Config-driven report model generator.

Reads all YAML configs under report_configs/ and generates a dbt SQL model
for each active report in models/Reporting_Statements/.

Design principle: Report engineers write YAML, not SQL templates.
The 100th report type should be as easy to add as the 1st.

Usage:
    python3 scripts/generate_report_models.py
    python3 scripts/generate_report_models.py --report custody_monthly
    python3 scripts/generate_report_models.py --dry-run   # Print without writing
    python3 scripts/generate_report_models.py --check     # Fail if output is stale (use in CI)

How it works:
    1. Reads each *.yml file in report_configs/
    2. Builds a SELECT statement using the config's columns, filters, and source
    3. Writes (or compares) models/Reporting_Statements/{report_id}.sql
    4. Writes a _Reporting_Statements__models.yml schema file with column docs

Why not just dbt macros?
    Macros work well for fixed patterns. This generator is better for
    report configs because:
    - Non-engineers (Finance, Compliance) can read and propose changes to YAML
    - Config files are reviewable in PRs without SQL knowledge
    - CI can detect stale generated SQL (--check flag)
    - Column labels, delivery metadata, audit config all live in one place
"""

import argparse
import hashlib
import sys
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).parent.parent
REPORT_CONFIGS_DIR = REPO_ROOT / "report_configs"
OUTPUT_DIR = REPO_ROOT / "models" / "Reporting_Statements"
SCHEMA_OUTPUT_PATH = OUTPUT_DIR / "_Reporting_Statements__models.yml"


def load_configs(report_id: str | None = None) -> list[dict]:
    """Load all active report configs, or a specific one by ID."""
    configs = []
    for config_path in sorted(REPORT_CONFIGS_DIR.glob("*.yml")):
        with open(config_path) as f:
            config = yaml.safe_load(f)
        if config.get("status") != "active":
            continue
        if report_id and config.get("report_id") != report_id:
            continue
        configs.append(config)
    return configs


def build_filter_clause(client_filters: list[dict]) -> str:
    """Convert client_filters list into a SQL WHERE clause."""
    if not client_filters:
        return ""

    conditions = []
    for filt in client_filters:
        field = filt["field"]
        op = filt["operator"]
        if op == "equals":
            val = filt["value"]
            if isinstance(val, str):
                conditions.append(f"  Source.{field} = '{val}'")
            elif isinstance(val, bool):
                conditions.append(f"  Source.{field} = {'TRUE' if val else 'FALSE'}")
            else:
                conditions.append(f"  Source.{field} = {val}")
        elif op == "in":
            vals = ", ".join(f"'{v}'" for v in filt["values"])
            conditions.append(f"  Source.{field} IN ({vals})")
        elif op == "not_equals":
            val = filt["value"]
            if isinstance(val, str):
                conditions.append(f"  Source.{field} != '{val}'")
            else:
                conditions.append(f"  Source.{field} != {val}")

    where_lines = "\n  AND ".join(conditions)
    return f"WHERE {where_lines}"


def build_select_clause(columns: list[dict]) -> str:
    """Build SELECT column list from config, sorted by order."""
    sorted_cols = sorted(columns, key=lambda c: c.get("order", 99))
    lines = []
    for i, col in enumerate(sorted_cols):
        comma = "  " if i == 0 else "  , "
        include_if = col.get("include_if")
        if include_if:
            # Conditional columns: CASE WHEN IsStakeable THEN col ELSE NULL END
            field_ref = include_if.split("=")[0].strip()
            lines.append(
                f"{comma}CASE\n"
                f"      WHEN Source.{field_ref} THEN Source.{col['name']}\n"
                f"      ELSE NULL\n"
                f"    END AS {col['name']}"
            )
        else:
            lines.append(f"{comma}Source.{col['name']} AS {col['name']}")
    return "\n".join(lines)


def generate_sql(config: dict) -> str:
    """Generate the full dbt SQL model for a report config."""
    report_id = config["report_id"]
    display_name = config["display_name"]
    description = config.get("description", "").strip()
    source_model = config["source_model"]
    columns = config.get("columns", [])
    client_filters = config.get("client_filters", [])

    # Build a fingerprint of the config so we can detect stale generated files
    config_fingerprint = hashlib.md5(
        yaml.dump(config, sort_keys=True).encode()
    ).hexdigest()[:8]

    select_clause = build_select_clause(columns)
    where_clause = build_filter_clause(client_filters)

    sql = f"""-- GENERATED BY scripts/generate_report_models.py
-- DO NOT EDIT THIS FILE DIRECTLY.
-- To modify this report, edit report_configs/{report_id}.yml and re-run the generator.
--
-- Report      : {display_name}
-- Report ID   : {report_id}
-- Config hash : {config_fingerprint}
-- Description : {description.replace(chr(10), chr(10) + "--               ")}

{{{{ config(
    materialized='view',
    tags=['reporting_statements']
) }}}}

SELECT
{select_clause}
FROM {{{{ ref('{source_model}') }}}} AS Source
{where_clause}
ORDER BY
  Source.CustomerName
  , Source.PositionPeriod
  , Source.Symbol
"""
    return sql


def generate_schema_yaml(configs: list[dict]) -> str:
    """Generate a dbt schema YAML for all report models."""
    models_list = []
    for config in configs:
        columns_list = []
        for col in sorted(config.get("columns", []), key=lambda c: c.get("order", 99)):
            label = col.get("label", col["name"])
            note = col.get("note", "")
            desc = label if not note else f"{label}. {note}"
            columns_list.append({"name": col["name"], "description": desc})

        models_list.append({
            "name": config["report_id"],
            "description": config.get("description", "").strip(),
            "columns": columns_list,
        })

    schema_doc = {"version": 2, "models": models_list}
    return yaml.dump(schema_doc, default_flow_style=False, allow_unicode=True, sort_keys=False)


def main():
    parser = argparse.ArgumentParser(description="Generate dbt SQL models from report configs")
    parser.add_argument("--report", help="Only generate for this report_id")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing files")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if generated SQL differs from what's on disk. Use in CI.",
    )
    args = parser.parse_args()

    configs = load_configs(report_id=args.report)

    if not configs:
        print(f"No active report configs found in {REPORT_CONFIGS_DIR}", file=sys.stderr)
        sys.exit(1)

    stale = []

    for config in configs:
        report_id = config["report_id"]
        sql = generate_sql(config)
        output_path = OUTPUT_DIR / f"{report_id}.sql"

        if args.dry_run:
            print(f"\n{'='*60}")
            print(f"Would write: {output_path}")
            print(f"{'='*60}")
            print(sql)
            continue

        if args.check:
            if output_path.exists():
                existing = output_path.read_text()
                if existing != sql:
                    print(f"STALE: {output_path} — re-run generate_report_models.py")
                    stale.append(report_id)
                else:
                    print(f"OK: {output_path}")
            else:
                print(f"MISSING: {output_path} — re-run generate_report_models.py")
                stale.append(report_id)
            continue

        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        output_path.write_text(sql)
        print(f"Generated: {output_path}")

    if not args.dry_run and not args.check:
        schema_yaml = generate_schema_yaml(configs)
        if not args.dry_run:
            SCHEMA_OUTPUT_PATH.write_text(schema_yaml)
            print(f"Generated: {SCHEMA_OUTPUT_PATH}")

    if stale:
        print(
            f"\nERROR: {len(stale)} report model(s) are stale: {', '.join(stale)}\n"
            "Run: python3 scripts/generate_report_models.py",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"\nDone. {len(configs)} report model(s) processed.")


if __name__ == "__main__":
    main()
